GET http://localhost:8080/api/welcome

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number": "2018234444",
  "password": "2018234444"
}

###
GET http://localhost:8080/swagger-ui/

###