spring:
  application:
    name: mybatis-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/mybatis-demo?
                   createDatabaseIfNotExist=true
                   &serverTimezone=Asia/Shanghai'
    username: root
    password: root
server:
  port: 8082


logging:
  level:
    root: warn
    edu:
      nefu: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'