spring:
  application:
    name: backend-examples
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/backend-examples?
                   createDatabaseIfNotExist=true
                   &serverTimezone=Asia/Shanghai'
    username: root
    password: root

  jackson:
    default-property-inclusion: non_null

my:
  secretkey: R28K42ZEJ8LWRHU5
  salt: 636eac2534bcfcb0
server:
  port: 8080


logging:
  level:
    root: warn
    edu:
      nefu: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://${dhost}/backend?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai
    username: ${username}
    password: ${password}

logging:
  level:
    com:
      example: info
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
